<!DOCTYPE html>
<html>
<head>
    <title>Feedback Report - {{ now()->format('F j, Y') }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .logo { width: 100px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .rating { color: #ffc107; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        .page-break { page-break-after: always; }
        .summary { margin-bottom: 20px; }
        .summary-item { margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Event Feedback Report</h1>
        <p>Generated on: {{ now()->format('F j, Y') }}</p>
        <p>Total Feedback Entries: {{ $feedbacks->count() }}</p>
    </div>
    
    <div class="summary">
        <h2>Summary</h2>
        <div class="summary-item">
            <strong>Average Rating:</strong> {{ number_format($feedbacks->avg('rating'), 1) }}/5
        </div>
        <div class="summary-item">
            <strong>Total Events with Feedback:</strong> {{ $feedbacks->groupBy('event_id')->count() }}
        </div>
        <div class="summary-item">
            <strong>Time Period:</strong> 
            @if($feedbacks->count() > 0)
                {{ $feedbacks->last()->created_at->format('M j, Y') }} to {{ $feedbacks->first()->created_at->format('M j, Y') }}
            @endif
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Email</th>
                <th>Event</th>
                <th>Rating</th>
                <th>Comments</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($feedbacks as $feedback)
            <tr>
                <td>{{ $feedback->name }}</td>
                <td>{{ $feedback->email }}</td>
                <td>{{ $feedback->event->title }}</td>
                <td>
                    @for($i = 1; $i <= 5; $i++)
                        @if($i <= $feedback->rating) ★ @else ☆ @endif
                    @endfor
                    ({{ $feedback->rating }}/5)
                </td>
                <td>{{ $feedback->comments }}</td>
                <td>{{ $feedback->created_at->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Report generated by EventSphere - College Event Management System</p>
        <p>Page {{ $PAGE_NUM }} of {{ $PAGE_COUNT }}</p>
    </div>
</body>
</html>